### ISSUE TITLE
this Plugin how to use ? has any example?

### ISSUE THREAD

**Issue by gaoxiang1** [iwer/GeoReference#1]

**Comment by iwer** [comment]
There is no dedicated example map in this plugin to keep things small. 
1. Put a GeoReferenceActor in your map, define which Lat/Lon your world origin should be. 
2. If you want to get Lat/Lon at a map location use GPSComponent->GetLatitude/GetLongitude. 
3. If you want to position an actor on a Lat/Lon, use the GeoLocationComponent as in BP_GeoLocComponentExample under Content/Blueprints.
